### ISSUE TITLE
Refused to connect issue

### ISSUE THREAD

**Issue by Luigi-Master** [Blobby-Boi/Cloaked-Site-File-Generator#1]
When I typed in the first url as poki.com and then the last box docs.google.com I pressed download file and opened it and it opens a tab saying poki refused to connect? I don't know, maybe its just the url.

**Comment by Blobby-Boi** [comment]
This is not an unblocker, as stated in the readme.md file. It's only meant to cloak websites, not unblock them.

**Comment by Luigi-Master** [comment]
Oh sorry
